name: CI

on:
  push:
    branches:
      - dev
      - master
      - tjj/codecov_v4_fork_test
  pull_request: ~

jobs:
  shared-ci:
    uses: TheJulianJES/workflows/.github/workflows/ci.yml@tjj/codecov_v4_and_token
    with:
      CODE_FOLDER: zhaquirks
      CACHE_VERSION: 3
      PYTHON_VERSION_DEFAULT: 3.12
      PRE_COMMIT_CACHE_PATH:  ~/.cache/pre-commit
      MINIMUM_COVERAGE_PERCENTAGE: 80
      PYTHON_MATRIX: "3.12"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
